# Site
title: RECREAZZZ.REPAIR
subtitle: the first place for a second chance

# URL
url: https://www.recreazzz.repair/
baseurl: /
permalink: :title/
include: ['_pages']

# Build settings
markdown: kramdown
port: 4666
future: true

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "post"